### ISSUE TITLE
useRechartToPng gives "Error: Invalid hook call"

### ISSUE THREAD

**Issue by brammitch** [brammitch/recharts-to-png#18]
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app

Currently troubleshooting...

**Comment by jsoutherland** [comment]
Hi @brammitch I was just coming back to report this.  If it helps this error went away when I embedded the javascript of the hook into my app:
```javascript
function useRechartToPng(options: Html2Canvas.Html2CanvasOptions = {}) {
  const [png, setPng] = React.useState(null);

  const ref = React.useCallback(async (node: any) => {
    if (node !== null && node?.container) {
      const data = await html2canvas(node.container, options).then((canvas) => canvas.toDataURL('image/png', 1.0));
      setPng(data);
    }
  }, [options])

  return [png, ref];
}
```

A co-worker mentioned it is a common error when a packaged lib leads to a second instance of react being included.

**Comment by brammitch** [comment]
> A co-worker mentioned it is a common error when a packaged lib leads to a second instance of react being included.

That was it! Nasty to track down and fix. Moved `react` and `react-dom` to peerDependencies, and used `rollup` to mark them as external. I have learned my lesson about having `react` in the dependencies.

After installing 0.8.1, I had to blow away my `package.lock` file and `node_modules` folder in order to make it work.
