### ISSUE TITLE
A Blank image is downloaded on click of download button.

### ISSUE THREAD

**Issue by parmodmalik** [brammitch/recharts-to-png#218]
A Blank image is downloaded on click of download button.

**Comment by brammitch** [comment]
What version of recharts-to-png is installed, and which function/hook are you using to generate the download?

I'm going to need to see some code to investigate. Do you have a repo or CodeSandbox that you can share?

**Comment by brammitch** [comment]
Closing this for now.

If you have any updates here, we can revisit it.
