### ISSUE TITLE
Multiple chart not work

### ISSUE THREAD

**Issue by rahadkc** [brammitch/recharts-to-png#3]
Thanks for the library, it nice to work with rechart. But I am facing a problem.

If I have multiple chart It doesn't work properly.
Is there a way to use multiple rechart to png image?

**Comment by brammitch** [comment]
You're welcome!

Can you provide a reproduction or more detail on your problem?

Does it not work when there are multiple charts on the same page?

In what way does it not work? Are you getting an error? Does it only download one of the charts regardless of how many are on the page?

**Comment by brammitch** [comment]
@rahadkc here is a quick [sandbox ](https://codesandbox.io/s/recharts-to-png-multi-chart-tnlu4?file=/src/App.js) example of downloading two different charts.

Does this do what you want it to do? This wouldn't scale well if you had a large number of charts though.

**Comment by brammitch** [comment]
Closing this issue until/unless there is any further discussion.
