### ISSUE TITLE
The problem that occurs when the page is scrolled.

### ISSUE THREAD

**Issue by hsynavc** [brammitch/recharts-to-png#317]
There is no problem when you click the download button at the top of the page. But when scrolling, the downloaded image is cropped. You can see the downloaded file after scrolling in the attachment. Thanks.
 
![1](https://user-images.githubusercontent.com/72340802/145438101-62753bb6-7066-47a0-ace6-01c263753666.PNG)
![area-chart ](https://user-images.githubusercontent.com/72340802/145438138-9ab6ad18-aaad-41b8-b299-4dce0ec70812.png)

**Comment by brammitch** [comment]
This was an issue with the html2canvas library (see https://github.com/niklasvh/html2canvas/pull/2625) but was fixed in 1.2.0. I'll update the html2canvas dependency for this library,
