### ISSUE TITLE
Composed Charts

### ISSUE THREAD

**Issue by john-rock** [brammitch/recharts-to-png#4]
Hello, are [composed charts](https://recharts.org/en-US/examples/LineBarAreaComposedChart) supported?

I have a bar and line graph inside a composed chart. After following the directions, it will only download an empty png.

**Comment by brammitch** [comment]
It has been working fine for me with composed charts: [Example](https://tnlu4.csb.app/). Chart 2 is a `<ComposedChart>`.

[Sandbox](https://codesandbox.io/s/recharts-to-png-multi-chart-tnlu4?file=/src/App.js)

If you have a reproduction of the issue or can share your code, I'd be happy to reopen this issue and take a look at it.

**Comment by john-rock** [comment]
Hi there, thaks for the response.

The link below is the component I am using the download feature on. Feel free to clone and see the behavior there.
[https://github.com/john-rock/benfords-law/blob/download-chart/src/components/Chart.js](
https://github.com/john-rock/benfords-law/blob/download-chart/src/components/Chart.js)

**Comment by brammitch** [comment]
Thanks for the repo. I'm not getting an empty png, but I think there may be some browser compatibility issues. Something is causing half of the png to be cut off in Chrome/Edge.

Here's the download in Chrome 86:
![chrome_86](https://user-images.githubusercontent.com/9699939/98744641-0d3fc080-2380-11eb-9b42-5cd209c62f37.png)

Here it is is Edge 86:
![edge_86](https://user-images.githubusercontent.com/9699939/98744664-16309200-2380-11eb-8c7a-ab03a1a65f7d.png)

And here's what it looks like in Firefox 78.4esr:
![firefox_78-4esr](https://user-images.githubusercontent.com/9699939/98744686-247eae00-2380-11eb-99fc-6a1b42d6f3c2.png)

I noticed you are using `<ResponsiveContainer>`, so I updated my Codesandbox in https://github.com/brammitch/recharts-to-png/issues/4#issuecomment-724848962 to use it as well, and it still works fine.

I'd dig into your styles/css to see if you can find out what is causing the issue, or you can pass in a `y-offset` to see if you can move the image into place, like so:
```javascript
const pngData = await getPngData(chart, {
      y: 500
    });
```

**Comment by john-rock** [comment]
Interesting, thanks for the quick response again.

I'll poke around and follow up with my findings.

**Comment by john-rock** [comment]
I ended up getting this to work correctly by moving the ref from the chart component and on to the container div as well as using the y offset option.

The downloaded chart is now viewing correct across all browsers.

**Comment by brammitch** [comment]
Awesome. Glad you were able to get it working!
