### ISSUE TITLE
Remove recharts dependency

### ISSUE THREAD

**Issue by dan-corneanu** [brammitch/recharts-to-png#634]
Hello,
I was successfully using this library to download charts, one at a time. However, now I need to download a single PNG with multiple charts on it. The charts are rendered inside a `<div>` container and I just need to create a PNG out of this div.

I've noticed that the only dependency to the `recharts` library is this line of code where you expect `ref.current.container` to have a `container` attribute
```
return await html2canvas(ref.current.container as HTMLElement, {
        logging: false,
        ...options,
})
```

Other than this, it looks like the `useCurrentPng` could be made generic and used to render any element to png. Am I right?
If yes, do you think it would be worth it to remove the dependency?

**Comment by brammitch** [comment]
@dan-corneanu Thanks for your suggestion. I created useGenerateImage to work with any `HTMLElement`. Can you try version `2.3.0-rc.0` and see if it works for you?

You can see examples of how to use it here:
https://github.com/brammitch/recharts-to-png/blob/42efb600f34f95dcba50fef1ef431ccd308ddfad/examples/next-pages/pages/index.tsx#L56-L74

**Comment by dan-corneanu** [comment]
@brammitch yes it does work as expected.

**Comment by brammitch** [comment]
@dan-corneanu Thanks for the feedback! I'll work on getting a proper release out as soon.
