### ISSUE TITLE
Verify compatibility with recharts-2.X

### ISSUE THREAD

**Issue by brammitch** [brammitch/recharts-to-png#64]
TODO:

- [ ] Test _recharts-to-png_ compatibility with Recharts 2

I have not yet had time to test if this library works with the newest version of Recharts. The project I developed this library for uses Recharts 1, and upgrading to Recharts 2 is not in our immediate roadmap.

Given that Recharts 2 was mostly about adding TypeScript, I'm hoping there are no issues.

If anyone is currently using this library with Recharts 2, does it perform as expected?

Has anyone used it with both Recharts 1 and 2?

**Comment by Allan690** [comment]
not sure if this could be a recharts 2 compatibilitty issue, but i'm getting blank pngs when i  download the png image.

**Comment by brammitch** [comment]
> not sure if this could be a recharts 2 compatibilitty issue, but i'm getting blank pngs when i download the png image.

@Allan690 do you have a repo you can share?

**Comment by brammitch** [comment]
Closed by e332880
